language: python
dist: xenial

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

env:
  - DJANGO_VERSION=2.2.x
  - DJANGO_VERSION=3.0.x
  - DJANGO_VERSION=3.1.x
  - DJANGO_VERSION=3.2.x

install:
  - pip install tox

script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"
